export const angarsData = [
    {
        id: "1",
        category: `two-skates`,
        title: "Двухскатный",
        long: "12",
        width: "6",
        height: "4",
        price: "468 000",
        installation: "2 000",
        image: '/img-4.webp',
    },
    {
        id: "2",
        category: `two-skates`,
        title: "Двухскатный",
        long: "12",
        width: "12",
        height: "5",
        price: "936 000",
        installation: "2 000",
        image: '/img-4.webp',
    },
    {
        id: "3",
        category: `two-skates`,
        title: "Двухскатный",
        long: "24",
        width: "12",
        height: "5",
        price: "1 872 000",
        installation: "2 000",
        image: '/img-4.webp',
    },
    {
        id: "4",
        category: `two-skates`,
        title: "Двухскатный",
        long: "36",
        width: "12",
        height: "6",
        price: "2 808 000",
        installation: "2 000",
        image: '/img-4.webp',
    },
    {
        id: "5",
        category: `two-skates`,
        title: "Двухскатный",
        long: "48",
        width: "12",
        height: "7",
        price: "3 744 000",
        installation: "2 000",
        image: '/img-4.webp',
    },
    {
        id: "6",
        category: `two-skates`,
        title: "Двухскатный",
        long: "54",
        width: "18",
        height: "7",
        price: "468 000",
        installation: "2 000",
        image: '/img-4.webp',
    },
    {
        id: "7",
        category: `rectangular`,
        title: "Прямостенные односкатные",
        long: "12",
        width: "6",
        height: "4",
        price: "432 000",
        installation: "2 000",
        image: '/img-4-2.webp',
    },
    {
        id: "8",
        category: `rectangular`,
        title: "Прямостенные односкатные",
        long: "12",
        width: "12",
        height: "5",
        price: "846 000",
        installation: "2 000",
        image: '/img-4-2.webp',
    },
    {
        id: "9",
        category: `rectangular`,
        title: "Прямостенные односкатные",
        long: "24",
        width: "12",
        height: "5",
        price: "1 728 000",
        installation: "2 000",
        image: '/img-4-2.webp',
    },
    {
        id: "10",
        category: `rectangular`,
        title: "Прямостенные односкатные",
        long: "36",
        width: "12",
        height: "6",
        price: "2 592 000",
        installation: "2 000",
        image: '/img-4-2.webp',
    },
    {
        id: "11",
        category: `rectangular`,
        title: "Прямостенные односкатные",
        long: "48",
        width: "12",
        height: "8",
        price: "3 456 000",
        installation: "2 000",
        image: '/img-4-2.webp',
    },
    {
        id: "12",
        category: `rectangular`,
        title: "Прямостенные односкатные",
        long: "60",
        width: "24",
        height: "8",
        price: "8 640 000",
        installation: "2 000",
        image: '/img-4-2.webp',
    },
    {
        id: "13",
        category: `bias`,
        title: "Прямостенные с уклоном",
        long: "12",
        width: "6",
        height: "4",
        price: "395 000",
        installation: "1 500",
        image: '/img-4-3.webp',
    },
    {
        id: "14",
        category: `bias`,
        title: "Прямостенные с уклоном",
        long: "12",
        width: "12",
        height: "5",
        price: "792 000",
        installation: "1 500",
        image: '/img-4-3.webp',
    },
    {
        id: "15",
        category: `bias`,
        title: "Прямостенные с уклоном",
        long: "24",
        width: "12",
        height: "6",
        price: "1 584 000",
        installation: "2 000",
        image: '/img-4-3.webp',
    },
    {
        id: "16",
        category: `bias`,
        title: "Прямостенные с уклоном",
        long: "36",
        width: "12",
        height: "6",
        price: "2 376 000",
        installation: "2 000",
        image: '/img-4-3.webp',
    },
    {
        id: "17",
        category: `bias`,
        title: "Прямостенные с уклоном",
        long: "48",
        width: "24",
        height: "6",
        price: "6 336 000",
        installation: "2 000",
        image: '/img-4-3.webp',
    },
    {
        id: "18",
        category: `bias`,
        title: "Прямостенные с уклоном",
        long: "54",
        width: "24",
        height: "8",
        price: "7 128 000",
        installation: "2 000",
        image: '/img-4-3.webp',
    },
];
